### ISSUE TITLE
React SSR

### ISSUE THREAD

**Issue by GR1ML0CK** [Adobe-Marketing-Cloud/aem-guides-wknd-events#14]
I got confirmation that React SSR would be a supported feature through the AEM SPA integration. Will this be something that will be added to this tutorial? If not, is there documentation and/or an example of this?

**Comment by godanny86** [comment]
hi @GR1ML0CK, yes this is something the tutorial will cover once a productized approach is released. Currently, SSR is available as a tech preview with the We.Retail Journal application. See [here](https://github.com/adobe/aem-sample-we-retail-journal/blob/master/react-app/DEVELOPMENT.md#running-the-local-nodejs-server-side-rendering) for details.
