### ISSUE TITLE
HierarchyNodeExporter issue

### ISSUE THREAD

**Issue by uppikaka** [Adobe-Marketing-Cloud/aem-guides-wknd-events#15]
could you please any one guide me. i'm  facing below issue, using AEM 6.4, with React integrating
"com.adobe.cq.export.json.hierarchy,version=[1.0,2) -- Cannot be resolved"
![image](https://user-images.githubusercontent.com/42263784/47570099-ebb73c00-d952-11e8-81d2-ead5da446cb8.png)

**Comment by godanny86** [comment]
Hi @uppikaka make sure that you have installed [SP2](https://helpx.adobe.com/experience-manager/6-4/release-notes/sp-release-notes.html). Also, while this shouldn't be necessary, you may try restarting AEM. 

The bundle that should get installed with SP2 is `com.adobe.cq.export.json 0.1.10`: 
![image](https://user-images.githubusercontent.com/8974514/47571656-12e81c00-d907-11e8-9672-4a1e33ed6d55.png)

**Comment by uppikaka** [comment]
Thank's @godanny86, i'm using  **Product : Adobe Experience Manager (6.4.0)**  not a [SP2](url) .i tryed com.adobe.cq.export.json 0.1.10: but not working, we have any other dependency for using **HierarchyNodeExperter** in AEM (6.4.0) for getting RootPage

**Comment by godanny86** [comment]
Hi @uppikaka you will need to Install Service Pack 2 on top of AEM 6.4. This service pack is freely available over Package share (just need an AdobeID to sign in). Here is the direct link: https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq640/servicepack/AEM-6.4.2.0
