### ISSUE TITLE
Composed React Components | WCM components 

### ISSUE THREAD

**Issue by bobbayunga** [Adobe-Marketing-Cloud/aem-guides-wknd-events#16]
I recently was working with the SPA editor WKND tutorial and I was thinking about a use case that isn't possible to use a React SPA component inside another React SPA editor Component. E.G. Make some kind of container Component that can insert other Spa react components. This would be a nice feature to implement.

I also wanted to use the WCM Tabs component inside the wknd-event pages but it couldn't render any element on the screen. Is is possible to use these components ?

(Yes I'm new in the AEM world :) )

**Comment by godanny86** [comment]
Hi @DriesVanbilloen! we can continue our conversation from forums here.

I'm still checking with engineering if the Tabs or Carousel components can be used but as it stands I'm not confident. Just looking at the JSON exported:

```
"tabs": {
"items": [
{
"url": null,
"title": "My tab 1",
"description": null,
"lastModified": null,
"path": "/content/wknd-events/react/home/first-article/jcr:content/root/responsivegrid/tabs/item_1"
},
{
"url": null,
"title": "My Tab 2",
"description": null,
"lastModified": null,
"path": "/content/wknd-events/react/home/first-article/jcr:content/root/responsivegrid/tabs/item_2"
}
],
"activeItem": "/content/wknd-events/react/home/first-article/jcr:content/root/responsivegrid/tabs/item_1"
}
```
The content does not seem to be exported so it will be difficult to MapTo. The other approach I think would be to create a new version of the Responsive Grid component (/libs/wcm/foundation/components/responsivegrid). I'll try and spin up an example later this afternoon to help...

**Comment by godanny86** [comment]
Looks like this is a known issue w/ the Tabs+Carousel components: https://github.com/adobe/aem-core-wcm-components/issues/298

**Comment by godanny86** [comment]
Hi @DriesVanbilloen check out https://github.com/godanny86/aem-guides-wknd-events/tree/feature/mygrid its a quick example on how to extend the responsive grid as a custom component. Not sure of your exact use case but might help. The fix for the Tabs/Carousel component should be coming soon..

![image](https://user-images.githubusercontent.com/8974514/47592129-fe744580-d93f-11e8-864d-cc51131de96d.png)

**Comment by bobbayunga** [comment]
I'll try it out, thanks for the help! I will wait for the solution of the tabs component. I think if I use the tabs component together with the custom responsive grid solution you provided. I can complete my usecase.
@godanny86 I don't know if I need to close this issues because it's related to the issues you mentioned. I'll let you decide 😄

**Comment by uppikaka** [comment]
Thanks for every one for the help! its working fine for me, because of not install SP2 in AEM 6.4 facing this issues

**Comment by godanny86** [comment]
Sounds good @DriesVanbilloen, I will close this since adobe/aem-core-wcm-components#298 is opened and we can track that.

**Comment by nick-khoury** [comment]
> 
> 
> Hi @DriesVanbilloen check out https://github.com/godanny86/aem-guides-wknd-events/tree/feature/mygrid its a quick example on how to extend the responsive grid as a custom component. Not sure of your exact use case but might help. The fix for the Tabs/Carousel component should be coming soon..
> 
> ![image](https://user-images.githubusercontent.com/8974514/47592129-fe744580-d93f-11e8-864d-cc51131de96d.png)

Question about this after trying it out. Why is it that I can no longer use the touch editor in AEM to publish content?

I see in your screenshot that you are able to edit the component and have the "Drag components here" box. For me it's as if I am viewing the page as published, which I'm not. I am using AEM 6.5.

**Comment by cqsapient** [comment]
Hi @DriesVanbilloen @nick-khoury 

Could you please let me know if you ever reached a solution? we are facing a similar issue where we need to have a tabs component which allows to drop any component in layout container in AEM SPA. The mygrid (responsivegrid extension) works fine independently but does not work(there is no author dialog overlay for layout container ) when  calling from inside another react component. Could you please let me know? cc @godanny86

**Comment by alissonxavierosfglobal** [comment]
Hi @DriesVanbilloen @nick-khoury, @godanny86  

I was needing to similar solution in Angular.

If someone has the solution please send me.

Thanks

**Comment by godanny86** [comment]
hi @alissonxavierosfglobal, @cqsapient I haven't experimented with latest Tab component. Currently (other than the Layout Container) the SPA editor doesn't support nesting of editable components. 

@pfauchere this seems to be a popular request, where is the appropriate place to log/track this feature request?
