### ISSUE TITLE
Getting Maven build errors when using the deployment plugin 

### ISSUE THREAD

**Issue by coatpont** [Adobe-Marketing-Cloud/aem-guides-wknd-events#21]
the error is as below: with the mvn clean install -PautoInstallPackage command after a simple clone. 
mvn clean install works fine, I can still do a manual install.

[WARNING] The POM for com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
[ERROR] Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd-events.ui.apps:[unknown-version], /Users/lebescon/Documents/Dev/aem-guides-wknd-events/ui.apps/pom.xml, line 34, column 16
[ERROR] Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
[ERROR] Unknown packaging: content-package @ com.adobe.aem.guides:aem-guides-wknd-events.ui.content:[unknown-version], /Users/lebescon/Documents/Dev/aem-guides-wknd-events/ui.content/pom.xml, line 34, column 16

**Comment by godanny86** [comment]
Hi @coatpont 
This seems to be a known issue with recent Maven archetypes. See https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/issues/131

Adding the `adobe-public` profile to the command will force the profile to be active:
```
mvn -PautoInstallPackage -Padobe-public clean install
```

@vladbailescu, I think this has come up several times and the `adobe-public` profile does not appear to be activated automatically (even though it is included in the POM). Perhaps it is worth investigating or we may need to update our documentation/instructions...

**Comment by coatpont** [comment]
thank you, that worked. Maybe we can update the .md file also?

**Comment by godanny86** [comment]
updated the Readme. Thanks @coatpont!
