### ISSUE TITLE
[React] Update Core Components dependency 2.2.2

### ISSUE THREAD

**Issue by godanny86** [Adobe-Marketing-Cloud/aem-guides-wknd-events#25]
Currently, the project uses Core Components 2.0.4. Several issues related JSON output of Core Components is fixed and therefore this project should be updated to the latest.

cc. @coatpont

**Comment by davidjgonzalez** [comment]
Probably should go direct to latest (2.2.2)

**Comment by godanny86** [comment]
fixed with PR #36
