### ISSUE TITLE
WKND Events - Core bundle is in installed state when running on AEM6.4.0

### ISSUE THREAD

**Issue by karthikgoli** [Adobe-Marketing-Cloud/aem-guides-wknd-events#44]
com.adobe.cq.export.json.hierarchy,version=[1.0,2) -- Cannot be resolved 
WKND Events -Core is in installed state beacuse of this.

**Comment by godanny86** [comment]
hi @karthikgoli do you have Service Pack 2 installed?

**Comment by karthikgoli** [comment]
No @godanny86

**Comment by godanny86** [comment]
You need AEM 6.4 + SP2 to go through the tutorial and use the SPA Editor. See https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-spa-wknd-tutorial-develop/react.html#local-dev-env
