### ISSUE TITLE
[React] Parsys and Mapped Components not appearing

### ISSUE THREAD

**Issue by aadams26** [Adobe-Marketing-Cloud/aem-guides-wknd-events#46]
Following the WKND tutorial, image and text components do not appear in author mode. 
* Heading "Welcome to AEM + React" present.
* Missing parsys.
* Confirmed that policy has **group:WKND Events - Content** as it's component group.
* Items appearing in JSON and sourcecode

```["text","image"],":items":{"text":{"richText":true,":type":"wknd-events/components/content/text"},"image":{"widths":[],"lazyEnabled":true,":type":"wknd-events/components/content/image"}}```

**Local environment setup confirmed.**

**Comment by godanny86** [comment]
hi @aadams26 is there any JavaScript errors in the browser? Have you tried clearing cookies/cache ad a fresh browser? You may also want to ensure AEM has not cached the clientlibrary by invalidating the cache: http://localhost:4502/libs/granite/ui/content/dumplibs.rebuild.html...

**Comment by aadams26** [comment]
Hi @godanny86 , I invalidated my clientlibs as instructed and it's still not working. Not convinced that a caching issue would be responsible for the components not appearing in the side rail...

**Comment by aadams26** [comment]
Hi @godanny86, it looks like caching was the issue. Perhaps that should be added to the Readme? Thanks for your help!

**Comment by godanny86** [comment]
hi @aadams26 glad that worked! Good call will add some troubleshooting info on the Readme.

**Comment by sathyalog** [comment]
I cleared cache by invalidating cache and rebuild libraries. But still components not appearing. Please find the below screenshot for reference.
<img width="1428" alt="screen shot 2019-02-27 at 7 30 39 pm" src="https://user-images.githubusercontent.com/3416121/53495696-7016f880-3ac6-11e9-839e-7d8e7d43e6ca.png">
@godanny86 Please help

**Comment by aadams26** [comment]
@Sathya are you on SP3?

**Comment by godanny86** [comment]
@sathyalog I would also verify that the wknd events core bundle is active (not in an Installed state): http://localhost:4502/system/console

**Comment by sathyalog** [comment]
> @sathya are you on SP3?
> […](#)
> On Feb 27, 2019, at 4:03 AM, Sathya ***@***.***> wrote: I cleared cache by invalidating cache and rebuild libraries. But still components not appearing. Please find the below screenshot for reference. @godanny86 Please help — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

No. i am using 6.4.0. I just verified console and i found the following error and its not in active state(just installed). @godanny86 
![error-aem](https://user-images.githubusercontent.com/3416121/53628187-5bef0a80-3c30-11e9-95de-eae6aeed69ac.png)

Please suggest next steps..

**Comment by aadams26** [comment]
@Sathya you’ll need to install service pack 3 as well.

**Comment by sathyalog** [comment]
> @sathya you’ll need to install service pack 3 as well.
> […](#)
> Sent from my iPhone
> On Feb 28, 2019, at 11:13 PM, Sathya ***@***.***> wrote: @sathya are you on SP3? … On Feb 27, 2019, at 4:03 AM, Sathya ***@***.***> wrote: I cleared cache by invalidating cache and rebuild libraries. But still components not appearing. Please find the below screenshot for reference. @godanny86 Please help — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread. No. i am using 6.4.0. I just verified console and i found the following error and its not in active state(just installed). @godanny86 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

I installed service pack 3 and its working as expected now. Thanks

**Comment by aadams26** [comment]
@sathya glad it’s working! The SPA SDK is tucked in service pack 3 which is why SPA components won’t work without it.
