### ISSUE TITLE
[React] Forced to use ReactJS components?

### ISSUE THREAD

**Issue by aadams26** [Adobe-Marketing-Cloud/aem-guides-wknd-events#47]
**Local Environment**
Confirmed.

**Describe the issue**
It appears that using a combination of server-side and client-side rendering components is prohibited in this implementation. Is this the case or is there a way to create an isomorphic application?

**Comment by aadams26** [comment]
Never mind, found this useful bit of info: 
https://helpx.adobe.com/experience-manager/6-4/sites/developing/using/spa-ssr.html

**Comment by godanny86** [comment]
hi @aadams26 yes there are plans to add an SSR chapter to the tutorial later this winter. Keep in mind that the approach outlined in https://helpx.adobe.com/experience-manager/6-4/sites/developing/using/spa-ssr.html is still considered a technical preview and not intended for a production rollout.

**Comment by aadams26** [comment]
@godanny86 I see that now. Thank you and looking forward to the SSR chapter!
