### ISSUE TITLE
[React] Parsys and Mapped Components not appearing 

### ISSUE THREAD

**Issue by sathyalog** [Adobe-Marketing-Cloud/aem-guides-wknd-events#48]
**Local Environment**
Before filing an issue, verify that the prerequisite tools/software are installed:

* AEM 6.4 + SP2
* Java 1.8
* Apache Maven (3.3.9 or newer)
* Node.js v10+
* npm 6+

**Describe the issue**
Following the WKND tutorial, image and text components do not appear in author mode.

**Screenshots**
<img width="1428" alt="screen shot 2019-02-27 at 7 30 39 pm" src="https://user-images.githubusercontent.com/3416121/53495878-d3a12600-3ac6-11e9-9e4a-934f6fb6df87.png">

**Additional context**
Followed @godanny86 comment here. https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/issues/46
I tried cleared cache by invalidating cache and rebuild libraries. But still components not appearing. Please find the screenshot for reference.
I am new to AEM and this React Integration as well. Please help.

**Comment by DiegoVanBelle** [comment]
I have the same issue. +1

**Comment by godanny86** [comment]
hi @sathyalog are you on 6.4.0? You need to have installed Service Pack 2 or higher (6.4.2 or 6.4.3). https://helpx.adobe.com/experience-manager/6-4/release-notes/sp-release-notes.html. 

You can verify the version of AEM by going to http://localhost:4502/libs/granite/operations/content/systemoverview.html

**Comment by godanny86** [comment]
Hi @sathyalog , @DiegoVanBelle were you able to get it working after installing Service pack 2 or 3 to your 6.4 instance?

**Comment by sathyalog** [comment]
Yes. We can close this. Thanks
