### ISSUE TITLE
[React] Code Splitting

### ISSUE THREAD

**Issue by GR1ML0CK** [Adobe-Marketing-Cloud/aem-guides-wknd-events#52]
Based on the guide, `aem-clientlib-generator` is used to convert the react bundles into AEM clientlibs. This seems to make code splitting not work since all the files get grouped into a single clientlib. Is there a way to still support code splitting to support cases where you might have components that are only for certain kinds of pages?

**Comment by godanny86** [comment]
hi @GR1ML0CK, great question. With the current capabilities of AEM clientlibs I do not believe this is possible. Do you mind re-posting this under https://github.com/adobe/aem-spa-project-archetype/issues

I think adding this as a feature in the archetype would be a good enhancement.
