### ISSUE TITLE
[React] Chapter 1 is not working in IE 11

### ISSUE THREAD

**Issue by epsilon-prasad** [Adobe-Marketing-Cloud/aem-guides-wknd-events#57]
**Local Environment**
Before filing an issue, verify that the prerequisite tools/software are installed:

* AEM 6.5 + SP2
* Java 1.8
* Apache Maven (3.3.9 or newer)
* Node.js v10+
* npm 6+

**Describe the issue**
Chapter-1 Editable components is not working in IE 11. But its working in chrome, firefox and Edge, In IE 11 i am getting blank screen with console error `Object doesn't support property or method 'endsWith'` 

`import 'es6-shim';
 import 'react-app-polyfill/ie9';
 import 'core-js/features/array/find';
 import 'core-js/features/array/includes';
 import 'core-js/features/number/is-nan';`

by import this packages in the `src/index.js` the above error is resolved but i am still get a blank screen in IE  without console error.

**Where in the tutorial are you experiencing an issue?**

In Chapter 1 in Step #6 
![console](https://user-images.githubusercontent.com/38847248/59912746-4f3b3000-9434-11e9-970d-6bd1b0b54f87.PNG)

**Comment by godanny86** [comment]
Hi @epsilon-prasad can you reproduce this issue when generating a new project using the SPA archetype? https://github.com/adobe/aem-spa-project-archetype.

As this project is based on the create-react-app I don't think IE11 is supported by default. You may need to add something like [react-app-polyfill](https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md) to your project. More info can be found [here](https://facebook.github.io/create-react-app/docs/supported-browsers-features#supported-browsers)

**Comment by epsilon-prasad** [comment]
Hi @godanny86, yes i am able to reproduce the issue.

i have updated the polyfill also 
Adding import 'react-app-polyfill/ie11';
import 'core-js'; in App/index.js. still i am getting blank screen in IE 11 only.

**Comment by godanny86** [comment]
would you mind filing an issue on the SPA Project archetype [0]? I think we need to get the recommended approach for IE 11 support from product engineering

cc. @pfauchere 

[0] -https://github.com/adobe/aem-spa-project-archetype/issues
