### ISSUE TITLE
[React] How to create a custom component in AEM and use it in React

### ISSUE THREAD

**Issue by psaksena85** [Adobe-Marketing-Cloud/aem-guides-wknd-events#63]
prerequisite tools/software are installed:

* AEM 6.4 + SP2
* Java 1.8
* Apache Maven (3.3.9 or newer)
* Node.js v10+
* npm 6+

**Comment by godanny86** [comment]
Hi @psaksena85,

You can see a net-new component developed by following the Hello World mini tutorial: https://helpx.adobe.com/experience-manager/kt/sites/using/spa-editor-helloworld-tutorial-use.html. It adds it to the We.Retail Project but the concepts are the same whether adding it to We.Retail, WKND or your customer project.

We still plan to add a custom component to the WKND SPA Editor tutorial, but will be delayed a bit. Another refernece will be too look at the Chapter 4 branch and the GMap component: https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/compare/react/chapter-3...react/chapter-4. this can give you an additional idea of how to develop a custom component.

**Comment by rojochen** [comment]
I saw We.Retail project only has created a component tutorial.

How to create the custom template in React?

If i create a template in the AEM Editor how to clone the content to my code base?

**Comment by psaksena** [comment]
Chapter 4 branch not there anymore

**Comment by godanny86** [comment]
yes @psaksena we removed that branch since parts of it were not up to date. If you need to create a net-new component I would follow: https://docs.adobe.com/content/help/en/experience-manager-learn/sites/spa-editor/spa-editor-helloworld-tutorial-use.html
