### ISSUE TITLE
[React] Unexpected error when viewing template in editor

### ISSUE THREAD

**Issue by clavearnel** [Adobe-Marketing-Cloud/aem-guides-wknd-events#64]
**Local Environment**
Before filing an issue, verify that the prerequisite tools/software are installed:

* AEM 6.3 
* Java 1.8
* Apache Maven (3.3.9 or newer)
* Node.js v10+
* npm 6+

**Describe the issue**
http://localhost:4502/editor.html/content/wknd-events/react/home.html
page is empty  white page only

**Where in the tutorial are you experiencing an issue?**
I get the finished project 
https://helpx.adobe.com/content/dam/help/en/experience-manager/kt/sites/using/getting-started-spa-wknd-tutorial-develop/react/jcr_content/main-pars/download_section/download-1/wknd-events-react-resources.zip

**Screenshots**

![image](https://user-images.githubusercontent.com/4475797/64169221-d9196780-ce7f-11e9-8ddc-86b7ce4d38f7.png)

**Comment by clavearnel** [comment]
we will try using 6.4 +sp2

**Comment by godanny86** [comment]
@clavearnel I believe for Template Editor support you need at least 6.4 + SP 5
