### ISSUE TITLE
[Angular] Please provide compability with Angular CLI 8

### ISSUE THREAD

**Issue by iameduardod** [Adobe-Marketing-Cloud/aem-guides-wknd-events#68]
Angular app fails to load when updated to Angular CLI 8. See attached error: 
![image](https://user-images.githubusercontent.com/29149580/68322938-fd651080-0089-11ea-86bf-04b660f4249f.png)

**Comment by AneleAndrew** [comment]
I Have the same issue, whats the update on this guys.?

**Comment by davidjgonzalez** [comment]
What version of Angular are you using? Are you using the target angular versions and only the CLI has been version bumped? Or has everything?

**Comment by AneleAndrew** [comment]
I downgraded my Angular CLI to 7.2.1 and problem solved.
