### ISSUE TITLE
[Angular] "[ERROR] Plugin com.github.eirslett:frontend-maven-plugin:1.6" when "mvn clean install"

### ISSUE THREAD

**Issue by kim257** [Adobe-Marketing-Cloud/aem-guides-wknd-events#69]
**Local Environment**
* AEM 6.5
* Java 1.8
* Apache Maven 3.6.2
* Node.js 10.16.3
* npm 6.9.0

**Describe the issue**
Install maven dependency in angular folder

>  [ERROR] Plugin com.github.eirslett:frontend-maven-plugin:1.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.github.eirslett:frontend-maven-plugin:jar:1.6: Could not transfer artifact com.github.eirslett:frontend-maven-plugin:pom:1.6 from/to adobe-public-releases (https://repo.adobe.com/nexus/content/groups/public): repo.adobe.com: Unknown host repo.adobe.com -> [Help 1]

**Where in the tutorial are you experiencing an issue?**
* Getting Started with Angular and AEM SPA Editor - Chapter 1
* Configure the frontend-maven-plugin Maven plugin
4 Within the angular-app folder run the following Maven command to trigger a build of the angular-app Maven project.

1. cd aem-guides-wknd-events/angular-app
2. mvn clean install

**Screenshots**
![image](https://user-images.githubusercontent.com/16816483/68661081-f5670e00-056c-11ea-82f5-4b3147e6af89.png)

**Comment by kim257** [comment]
> https://repo.adobe.com/nexus/content/groups/public
Not found `com.github.eirslett:frontend-maven-plugin`

![image](https://user-images.githubusercontent.com/16816483/68822598-e9da2b00-06c3-11ea-8318-e426882ce422.png)

**Comment by godanny86** [comment]
Hi @kim257 The frontend maven plugin should get downloaded from central maven repo: https://repo.maven.apache.org/maven2/com/github/eirslett/frontend-maven-plugin/1.6/

what version of Maven are you running? I thought the default was that it would look for central maven first...

**Comment by kim257** [comment]
Thank you for reply @godanny86 

mvn 3.6.2
![image](https://user-images.githubusercontent.com/16816483/68825461-c5368100-06cc-11ea-82f2-edf7635baeb9.png)

I created setting.xml  like this url.
https://helpx.adobe.com/experience-manager/kb/SetUpTheAdobeMavenRepository.html

**Comment by kim257** [comment]
Thank you @godanny86  ,Because own proxy

**Comment by godanny86** [comment]
glad it worked out!
