### ISSUE TITLE
[Angular] Archetype discrepancies with Wknd Events code repo

### ISSUE THREAD

**Issue by iameduardod** [Adobe-Marketing-Cloud/aem-guides-wknd-events#70]
The [angular archetype ](https://github.com/adobe/aem-spa-project-archetype/tree/master/src/test/resources/projects/angular/reference/angular-app)and overall code structure is fundamentally and operationally different from the [Wknd Events repo](https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/tree/angular/chapter-8). 

Examples:
Router: [Wknd](https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/blob/angular/chapter-8/angular-app/src/app/app-routing.module.ts) vs [AEM SPA Archetype](https://github.com/adobe/aem-spa-project-archetype/blob/master/src/main/resources/archetype-resources/angular-app/src/app/app-routing.module.ts)
Page component: [Wknd](https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/blob/angular/chapter-8/angular-app/src/app/components/page/page.component.ts) vs [AEM SPA Archetype](https://github.com/adobe/aem-spa-project-archetype/blob/master/src/main/resources/archetype-resources/angular-app/src/app/components/page/page.component.ts)
App Module: [Wknd](https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/blob/angular/chapter-8/angular-app/src/app/app.module.ts) vs [AEM SPA Archetype](https://github.com/adobe/aem-spa-project-archetype/blob/master/src/main/resources/archetype-resources/angular-app/src/app/app.module.ts)

**Which approach is the more correct way of doing AEM SPA apps?**

**Comment by godanny86** [comment]
Hi @emd2013 great question and our apologies but the tutorial has lagged behind the archetype. Please use the tutorial to learn and understand the basic concepts of the SPA Editor. For your own project and implementation please use the SPA archetype and follow those standards. We plan to revise the WKND events tutorial to follow the archetype more closely.
