### ISSUE TITLE
[React] which archetype is used to generate wknd-event

### ISSUE THREAD

**Issue by gplsek** [Adobe-Marketing-Cloud/aem-guides-wknd-events#76]
I was hoping to use same set up for a new AEM react project and when setting up a project using
mvn archetype:generate \
 -DarchetypeGroupId=com.adobe.granite.archetypes \
 -DarchetypeArtifactId=aem-project-archetype \
 -DarchetypeVersion=22

And following the react sample , few things seem to be missing and I cant get the react app to bind to my pages ?

sorry very new to AEM

**Comment by godanny86** [comment]
Hi @gplsek, no problem! Unfortunately we are in the middle of a transition and it is a bit confusing.

The long term goal is to eventually have a single Project Archetype that can be used for traditional or SPA AEM projects: https://github.com/adobe/aem-project-archetype. The React/Angular support will not be available until archetype version **23** is released. I'm not sure of the timing but probably within the next couple of weeks...

So what this means is that in the interim use https://github.com/adobe/aem-spa-project-archetype/releases/tag/v4.0.0. Once archetype version 23 is released, for any new projects, use that... Sorry for the confusion!

**Comment by gplsek** [comment]
thank you !!
