### ISSUE TITLE
[React] Unable to edit components in child pages

### ISSUE THREAD

**Issue by sachinsharma19** [Adobe-Marketing-Cloud/aem-guides-wknd-events#77]
**Local Environment**

* AEM 6.5.0
* Java 1.8
* Apache Maven - (3.6.2)
* Node.js - 13.3.0
* npm - 6.13.1

![image](https://user-images.githubusercontent.com/59455318/71694504-606adf00-2d7d-11ea-9130-8d3d55ea74b5.png)

In Chapter 3, After Step # 9 for List component ->

I can edit home page but later on when I created two child pages in AEM,  I noticed they are not editable. I have followed all the steps so not sure what else I am missing.

**Comment by godanny86** [comment]
@sachinsharma19 if you refresh the page do they become editable? Is the same behavior observed when using an incognito window / fresh browser?

**Comment by sachinsharma19** [comment]
Unfortunately it doesn't become editable after refresh as well as in Incognito window.

**Comment by sachinsharma19** [comment]
@godanny86 I reinstalled everything and it's working now.
