### ISSUE TITLE
java.lang.NullPointerException when trying chatper 2 of Angular SPA

### ISSUE THREAD

**Issue by vidhyabhushanbahl** [Adobe-Marketing-Cloud/aem-guides-wknd-events#81]
**Local Environment**
Before filing an issue verify that the prerequisite tools/software are installed:

* AEM 6.4 + SP2
* Java 1.8
* Apache Maven (3.3.9 or newer)
* Node.js v10+
* npm 6+

**Describe the issue**
Downloaded the code from github and trying step 9 at
https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-spa-wknd-tutorial-develop/angular/chapter-2.html

Getting error on browser console as 505 and in error.log 

`com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.adobe.aem.guides.wkndevents.core.models.impl.HierarchyPageImpl[":children"]->java.util.LinkedHashMap["/content/wknd-events/angular/home"]->com.adobe.aem.guides.wkndevents.core.models.impl.HierarchyPageImpl[":items"]->java.util.LinkedHashMap["root"]->com.day.cq.wcm.foundation.model.responsivegrid.ResponsiveGrid[":items"]->java.util.LinkedHashMap["responsivegrid"]->com.day.cq.wcm.foundation.model.responsivegrid.ResponsiveColumn["exportedComponent"]->com.day.cq.wcm.foundation.model.responsivegrid.ResponsiveGrid[":items"]->java.util.LinkedHashMap["image"]->com.day.cq.wcm.foundation.model.responsivegrid.ResponsiveColumn["exportedComponent"]->com.adobe.cq.wcm.core.components.internal.models.v2.ImageImpl["areas"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391) [com.fasterxml.jackson.core.jackson-databind:2.9.5]

`

**Comment by godanny86** [comment]
hi @vidhyabhushanbahl what version of Core Components are installed? It looks like you are hitting: https://github.com/adobe/aem-core-wcm-components/issues/887. You need to downgrade to Core Components v. 2.7.0. The issue has been fixed but we will need to wait until 2.9.0 release...

**Comment by vidhyabhushanbahl** [comment]
It worked. thanks
