### ISSUE TITLE
[React] Error loading page with SPA with AEM 6.2

### ISSUE THREAD

**Issue by sajith4u** [Adobe-Marketing-Cloud/aem-guides-wknd-events#85]
**Local Environment**

* AEM 6.2 + SP2
* Java 1.8
* Apache Maven (3.6.3)
* Node.js v14.3.0
* npm 6.14.5

**Describe the issue**
When Deploy in local environment it gives this error. I need to know SSR support in AEM 6.2. This is the tutorial I have followed.

https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-spa-wknd-tutorial-develop/react/chapter-0.html#prerequisites

**Screenshots**
![image](https://user-images.githubusercontent.com/4838105/83620677-4727c200-a5ab-11ea-886a-4f2a2822e3d1.png)

**Comment by godanny86** [comment]
hi @sajith4u the AEM SPA Editor feature supports AEM 6.4 + SP2 at a minimum. AEM 6.2 is not supported.

**Comment by sajith4u** [comment]
@godanny86 Thanks for rely.
